apiVersion: v1
kind: Service
metadata:
  labels:
    app: exercise-3
  name: exercise-3-service
  namespace: exercise-3
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: exercise-3
  type: LoadBalancer
