apiVersion: v1
kind: Service
metadata:
  labels:
    app: exercise-1
  name: exercise-1-service
  namespace: exercise-1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: exercise-1
  type: LoadBalancer
