apiVersion: v1
kind: Service
metadata:
  labels:
    app: exercise-2
  name: exercise-2-service
  namespace: exercise-2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: exercise-2
  type: LoadBalancer
