apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: exercise-5
  name: exercise-5-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise-5
  template:
    metadata:
        labels:
          app: exercise-5
    spec:
      initContainers:
      - image: ubuntu:latest
        name: sleepy
        args:
          - "sleep"
          - "10"
      containers:
      - image: 235156212133.dkr.ecr.us-east-1.amazonaws.com/httpd-jake:0.0.1
        name: httpd-jake
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 50Mi
          limits:
            memory: 50Mi
