apiVersion: v1
kind: Service
metadata:
  labels:
    app: karma-redis
  name: karma-redis
  namespace: exercise-4
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: karma-redis
  sessionAffinity: None
  type: ClusterIP
