---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: karma-app
  name: karma-app
  namespace: exercise-4
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: karma-app
  type: LoadBalancer
