apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: exercise-2
  name: exercise-2-deployment
  namespace: exercise-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise-2
  template:
    metadata:
        labels:
          app: exercise-2
    spec:
      containers:
      - image: nginx:1.14.1
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 50Mi
          limits:
            memory: 50Mi
