apiVersion: v1
kind: Service
metadata:
  labels:
    app: exercise-5
  name: exercise-5-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: exercise-5
  type: LoadBalancer
